// v0.23.1 visual evidence capture ( §§16-17) — CAPTURE-ONLY tooling.
// Runs ONLY with SEED_CAPTURE=1; normal `npm run test:e2e` skips this file
// so evidence is never regenerated by routine runs. Output is immutable:
// docs/visual_audit_v0231/01..15. Status: EVIDENCE_CAPTURED,
// HUMAN_REVIEW_PENDING — never self-declared PASS.
// Quality: player-like state, no QA/debug overlays, no 1e9 HP
// (cleanPresentation before every shot), no impossible values.
import { test, expect } from "@playwright/test";
import { startRun, drainDrafts } from "./helpers";

test.skip(process.env.SEED_CAPTURE !== "1", "capture-only: run with SEED_CAPTURE=1");

declare global {
  interface Window {
    __seedE2E?: {
      grant: (n: number) => void;
      advance: (s: number) => void;
      teleportToPOI: () => boolean;
      tryClaim: () => string;
      claimFirst: () => string;
      openSpecPicker: (poiId?: string) => void;
      readyAscend: () => void;
      cleanPresentation: () => void;
      snapshot: () => string;
    };
  }
}

const SHOTS = "docs/visual_audit_v0231";

test.setTimeout(600000);

test("capture v0231 visual evidence set (TH)", async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 720 });
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(e.message));

  async function shot(name: string): Promise<void> {
    await page.evaluate(() => window.__seedE2E?.cleanPresentation());
    await page.waitForTimeout(200);
    await page.screenshot({ path: `${SHOTS}/${name}` });
  }

  // Fresh TH tutorial run: intro modal first.
  await startRun(page, "EPOCH-VIS-01", { tutorialCompleted: false, lang: "th" });
  await expect(page.locator("#tutorial-intro-screen")).toBeVisible();
  await shot("01_tutorial_no_overlap_th.png");
  await page.locator("#tutorial-next-btn").click();
  await page.locator("#tutorial-start-btn").click();
  await expect(page.locator("#tutorial-intro-screen")).toHaveCount(0);

  // Claim prompt on a clear staged site (teleport + minimal advance keeps
  // distant spawns outside the clear radius).
  await page.evaluate(() => window.__seedE2E?.teleportToPOI());
  await page.evaluate(() => window.__seedE2E?.advance(1));
  await expect(page.locator(".terr-claim-btn")).toBeVisible({ timeout: 15000 });
  await shot("09_site_claim_prompt.png");

  // Claim for real (unspecialized), then the specialization cards.
  const claimed: string = await page.evaluate(() => window.__seedE2E?.tryClaim() ?? "");
  if (claimed !== "") {
    await page.locator(".terr-spec-btn").click();
  } else {
    await page.evaluate(() => window.__seedE2E?.claimFirst() ?? "");
    await page.evaluate(() => window.__seedE2E?.openSpecPicker());
  }
  await expect(page.locator("#spec-screen")).toBeVisible({ timeout: 15000 });
  expect(await page.locator("#spec-screen .btn").count()).toBeGreaterThanOrEqual(3);
  await shot("10_outpost_spec_cards.png");
  await page.locator("#spec-screen .btn").first().click();
  await expect(page.locator("#spec-screen")).toHaveCount(0);

  // Civ map selected outpost (early: T1, hold not yet satisfied).
  // Click the true CSS center (canvas attr pixels are CSS-stretched).
  async function clickMapCenter(): Promise<void> {
    const cvBox = await page.locator("#civmap-screen canvas").boundingBox();
    expect(cvBox).toBeTruthy();
    await page.mouse.click(cvBox!.x + cvBox!.width / 2, cvBox!.y + cvBox!.height / 2);
  }
  await page.keyboard.press("M");
  await expect(page.locator("#civmap-screen")).toBeVisible();
  await clickMapCenter();
  await expect(page.locator("#civmap-detail .civmap-detail-name")).toBeVisible({ timeout: 5000 });
  await shot("11_civmap_selected_outpost.png");
  await page.keyboard.press("M");

  // Hold satisfies: upgrade cost line appears on the same panel.
  // Tracking persists across map sessions — no second click (clicking the
  // tracked site would untoggle it).
  await page.evaluate(() => window.__seedE2E?.advance(95));
  await page.keyboard.press("M");
  await expect(page.locator("#civmap-screen")).toBeVisible();
  await expect(page.locator("#civmap-detail .civmap-detail-name")).toBeVisible({ timeout: 5000 });
  await expect(page.locator("#civmap-detail")).toContainText(/ค่าอัปเกรด|ความรู้ยังไม่พอ/);
  await shot("12_upgrade_cost.png");
  await page.keyboard.press("M");

  // Legacy cards through the real ascend offer (continues into world 2).
  await page.evaluate(() => window.__seedE2E?.readyAscend());
  await page.locator(".hud-ascend button").click();
  await expect(page.locator("#legacy-screen")).toBeVisible({ timeout: 15000 });
  expect(await page.locator("#legacy-screen .card").count()).toBeGreaterThanOrEqual(1);
  await shot("14_legacy_cards.png");
  await page.locator("#legacy-screen .card").first().click();
  await expect(page.locator("#origin-screen")).toBeVisible({ timeout: 15000 });
  await page.locator("#origin-screen .card").first().click();
  // Ascension completes into world 2 (snapshot truth, like regression).
  // No second intro by design: the tutorial continues across ascension.
  await expect(async () => {
    const snap = JSON.parse((await page.evaluate(() => window.__seedE2E?.snapshot() ?? "{}")) as string) as {
      id?: Array<string | number>;
    };
    expect(snap.id?.[3]).toBe(1);
  }).toPass({ timeout: 15000 });
  await expect(page.locator(".hud")).toBeVisible({ timeout: 15000 });

  // Pause + field guide in TH.
  await page.keyboard.press("Escape");
  await expect(page.locator("#pause-screen")).toBeVisible();
  await shot("02_pause_menu_th.png");
  await page.locator("#pause-screen").getByRole("button", { name: "คู่มือและปุ่มควบคุม" }).click();
  await expect(page.locator("#guide-screen")).toBeVisible();
  const guideAlign = await page.locator(".guide-content p").first().evaluate(
    (el) => getComputedStyle(el).textAlign,
  );
  expect(guideAlign).toBe("left");
  await shot("03_field_guide_th.png");
  await page.locator("#guide-screen").getByRole("button", { name: "กลับ" }).click();
  await page.keyboard.press("Escape");
  await expect(page.locator("#pause-screen")).toHaveCount(0);

  // Draft cards in TH, then the reroll feedback (NEW badge or empty toast).
  await page.evaluate(() => window.__seedE2E?.grant(30));
  await expect(page.locator("#draft-screen")).toBeVisible({ timeout: 15000 });
  await shot("04_draft_cards_th.png");
  await page.locator("#draft-screen .card-reserve").first().click();
  await page.locator("#draft-screen").getByRole("button", { name: /^สุ่มใหม่/ }).click();
  const badge = page.locator("#draft-screen .card-new");
  const toast = page.locator(".toast");
  await expect(async () => {
    const b = await badge.count();
    const t = await toast.count();
    expect(b > 0 || t > 0).toBe(true);
  }).toPass({ timeout: 10000 });
  if ((await badge.count()) > 0) {
    // NEW badge must sit inside its card without covering the reserve button.
    const cardBox = await page.locator("#draft-screen .card").first().boundingBox();
    const badgeBox = await badge.first().boundingBox();
    const rsBox = await page.locator("#draft-screen .card-reserve").first().boundingBox();
    expect(cardBox && badgeBox && rsBox).toBeTruthy();
    if (cardBox && badgeBox) {
      expect(badgeBox.x >= cardBox.x - 1 && badgeBox.x + badgeBox.width <= cardBox.x + cardBox.width + 1).toBe(true);
    }
    if (badgeBox && rsBox) {
      const overlap = badgeBox.x < rsBox.x + rsBox.width && rsBox.x < badgeBox.x + badgeBox.width &&
        badgeBox.y < rsBox.y + rsBox.height && rsBox.y < badgeBox.y + badgeBox.height;
      expect(overlap).toBe(false);
    }
  }
  await shot("05_reroll_changed.png");
  // Drain the whole queued draft chain before overlays (T/M need no draft).
  await drainDrafts(page);
  await expect(page.locator("#draft-screen")).toHaveCount(0);

  // Tech map CURRENT early, then mid (owned techs), then OVERVIEW.
  await page.keyboard.press("T");
  await expect(page.locator("#techmap-screen")).toBeVisible();
  await shot("06_techmap_current_early.png");
  await page.keyboard.press("T");
  // Tech map CURRENT mid (several owned techs), then OVERVIEW.
  await page.evaluate(() => window.__seedE2E?.grant(800));
  await expect(page.locator("#draft-screen")).toBeVisible({ timeout: 15000 });
  await drainDrafts(page);
  await expect(page.locator("#draft-screen")).toHaveCount(0);
  await page.keyboard.press("T");
  await expect(page.locator("#techmap-screen")).toBeVisible();
  await shot("07_techmap_current_mid.png");
  await page.locator(".techmap-btn-fit").click();
  await page.waitForTimeout(400);
  await shot("08_techmap_overview.png");
  await page.keyboard.press("T");

  // Command context: disclosed squad/command dock after a real claim.
  await expect(page.locator(".status-squad")).toBeVisible();
  await shot("13_command_context.png");

  // 200% TH pause: sections reachable via internal scroll, still readable.
  await page.keyboard.press("Escape");
  await expect(page.locator("#pause-screen")).toBeVisible();
  await page.locator("#pause-screen").getByRole("button", { name: "200%", exact: true }).click();
  await shot("15_ui200_th.png");
  await page.keyboard.press("Escape");
  await expect(page.locator("#pause-screen")).toHaveCount(0);

  expect(errors).toEqual([]);
});
