// qa:report — sanitized, repo-safe playtest summary (committable).
// Reads test-results/human-playtests/latest.json, writes
// docs/playtests/latest-v0231-interaction-human.md with project evidence ONLY.
// Raw environment fingerprints / local paths / user data never leave the machine.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LATEST = join(ROOT, "test-results", "human-playtests", "latest.json");

export function getReportOutputPath(snap, rootDir = ROOT) {
  const content = snap?.versions?.content ?? 0;
  return join(rootDir, "docs", "playtests", content >= 8 ? "latest-v026-experience-human.md" : "latest-v0231-interaction-human.md");
}

const f2 = (n) => (Number.isFinite(n) ? n.toFixed(2) : "n/a");

/** Build the sanitized markdown from a raw recorder snapshot. Pure-ish, tested. */
export function buildSanitizedMarkdown(snap) {
  const L = [];
  const cps = snap.checkpoints ?? [];
  const at = (name) => cps.find((c) => c.event === name);
  const t = (name) => {
    const c = at(name);
    return c ? `${f2(c.simTime)}s sim` : "NOT REACHED";
  };
  const content = snap?.versions?.content ?? 0;
  if (content >= 8) {
    L.push(`# -SEED v0.26 Experience Evidence Human — Sanitized Evidence`);
  } else {
    L.push(`# -SEED v0.23.1 Interaction Clarity Human — Sanitized Evidence`);
  }
  L.push(``);
  L.push(`> Auto-generated by \`npm run qa:report\` from local QA telemetry.`);
  L.push(`> Machine evidence only — fun and readability verdicts need a human.`);
  L.push(``);
  L.push(`## Run`);
  L.push(``);
  L.push(`- sessionId: ${snap.sessionId ?? "unknown"}`);
  L.push(`- reportSequence: ${snap.reportSequence ?? 1}`);
  L.push(`- seed: ${snap.seed ?? "unknown"}`);
  L.push(`- origin: ${snap.originId ?? snap.engagement?.[0]?.origin ?? "unknown"}`);
  if (snap.worldTraits && snap.worldTraits.length > 0) {
    L.push(`- worldTraits: ${snap.worldTraits.join(", ")}`);
  }
  L.push(`- package: ${snap.versions?.packageVersion ?? "?"} / worldgen ${snap.versions?.worldgen ?? "?"} / content ${snap.versions?.content ?? "?"} / save ${snap.versions?.saveSchema ?? "?"}`);
  L.push(`- endReason: ${snap.endReason || "NOT FINISHED"}`);
  if (snap.wallStart && snap.wallEnd) {
    L.push(`- wallDuration: ${f2((snap.wallEnd - snap.wallStart) / 1000)}s`);
  }
  L.push(`- viewport: ${snap.environment?.viewport ?? "?"} / refresh: ${snap.environment?.refreshHz ?? "?"}`);
  L.push(``);
  L.push(`## Route`);
  for (const [ev, label] of [
    ["RUN_START", "run started"], ["BRONZE_REACHED", "Bronze"], ["IRON_REACHED", "Iron"],
    ["INDUSTRIAL_REACHED", "Industrial"], ["ATOMIC_REACHED", "Atomic"], ["SPACE_REACHED", "Space"],
    ["BOSS_SPAWNED", "boss spawned"], ["BOSS_KILLED", "boss killed"],
    ["ASCENSION_OFFERED", "ascension offered"], ["ASCENSION_STARTED", "ascension started"],
    ["CHILD_WORLD_STARTED", "child world"],
    ["POST_ASCENSION_30S", "post-ascension +30s"],
    ["POST_ASCENSION_60S", "post-ascension +60s"],
    ["POST_ASCENSION_120S", "post-ascension +120s"],
    ["PLAYER_DIED", "player died"], ["RUN_END", "run ended"],
  ]) {
    L.push(`- [${at(ev) ? "x" : " "}] ${label} ${at(ev) ? `(${f2(at(ev).simTime)}s)` : ""}`);
  }
  L.push(``);
  L.push(`## Civilization Command Loop Usage`);
  L.push(``);
  const marks = snap.simMarks ?? [];
  const techMapOpens = marks.filter((m) => m.kind === "techmap_open").length;
  const firstTechMap = marks.find((m) => m.kind === "techmap_open");
  const firstTechMapTime = firstTechMap ? `${f2(firstTechMap.simTime)}s sim` : "NEVER";
  const pinMarks = marks.filter((m) => m.kind === "pin");
  const pinnedIds = [...new Set(pinMarks.map((m) => m.detail))];
  const reserveCount = marks.filter((m) => m.kind === "draft_reserve").length;
  const reserveAtt = marks.filter((m) => m.kind === "reserve_attempt").length;
  const rerollCount = marks.filter((m) => m.kind === "draft_reroll").length;
  const rerollAtt = marks.filter((m) => m.kind === "reroll_attempt").length;
  const rerollUn = marks.filter((m) => m.kind === "reroll_unavailable").length;
  const skipCount = marks.filter((m) => m.kind === "draft_skip").length;
  const breakthroughMarks = marks.filter((m) => m.kind === "breakthrough");
  const breakthroughIds = [...new Set(breakthroughMarks.map((m) => m.detail))];

  const territoryMarks = marks.filter((m) => m.kind === "territory_claimed");
  const claimAtt = marks.filter((m) => m.kind === "claim_attempt").length;
  const firstTerritory = territoryMarks[0];
  const firstTerritoryTime = firstTerritory ? `${f2(firstTerritory.simTime)}s sim` : "NEVER";
  const specMarks = marks.filter((m) => m.kind === "outpost_spec");
  const specR = specMarks.filter((m) => m.detail.endsWith(":research")).length;
  const specM = specMarks.filter((m) => m.detail.endsWith(":military")).length;
  const specE = specMarks.filter((m) => m.detail.endsWith(":economy")).length;
  const upgrades = marks.filter((m) => m.kind === "outpost_upgraded").length;
  const upgradeAtt = marks.filter((m) => m.kind === "upgrade_attempt").length;
  const raidsIn = marks.filter((m) => m.kind === "raid_incoming").length;
  const raidsDef = marks.filter((m) => m.kind === "raid_repelled").length;
  const raidsLost = marks.filter((m) => m.kind === "outpost_lost").length;
  const outpostsRepaired = marks.filter((m) => m.kind === "outpost_repaired").length;

  const rallyCount = marks.filter((m) => m.kind === "squad_command" && m.detail === "follow").length;
  const focusCount = marks.filter((m) => m.kind === "squad_command" && m.detail === "focus").length;
  const holdCount = marks.filter((m) => m.kind === "squad_command" && m.detail === "hold").length;
  const abilityCount = marks.filter((m) => m.kind === "ability_used").length;
  const civMapOpens = marks.filter((m) => m.kind === "civmap_open").length;

  L.push(`- Tech Map opened: ${techMapOpens}`);
  L.push(`- First Tech Map open: ${firstTechMapTime}`);
  L.push(`- Paths pinned: ${pinMarks.length} [${pinnedIds.join(", ") || "-"}]`);
  L.push(`- Reserve uses: ${reserveCount} (attempts ${reserveAtt})`);
  L.push(`- Rerolls: ${rerollCount} (attempts ${rerollAtt}, unavailable ${rerollUn})`);
  L.push(`- Skips: ${skipCount}`);
  L.push(`- Breakthroughs completed: ${breakthroughMarks.length} [${breakthroughIds.join(", ") || "-"}]`);
  L.push(``);
  L.push(`- Territories claimed: ${territoryMarks.length} [${territoryMarks.map((m) => m.detail.split(":")[1]).filter(Boolean).join(", ") || "-"}] (claim attempts ${claimAtt})`);
  L.push(`- First territory time: ${firstTerritoryTime}`);
  L.push(`- Outpost types: [Research: ${specR}, Military: ${specM}, Economy: ${specE}]`);
  L.push(`- Outpost upgrades: ${upgrades} (attempts ${upgradeAtt})`);
  L.push(`- Raids incoming: ${raidsIn}`);
  L.push(`- Raids defended: ${raidsDef}`);
  L.push(`- Raids lost: ${raidsLost}`);
  L.push(`- Outposts repaired: ${outpostsRepaired}`);
  L.push(``);
  L.push(`- Rally commands (Q): ${rallyCount}`);
  L.push(`- Focus commands (E): ${focusCount}`);
  L.push(`- Hold commands (R): ${holdCount}`);
  L.push(`- Origin ability uses (F): ${abilityCount}`);
  L.push(`- Civ Map opens (M): ${civMapOpens}`);
  L.push(``);
  L.push(`- Age gate block summary:`);
  const cStone = at("STONE_START");
  const cBronze = at("BRONZE_REACHED");
  const cIron = at("IRON_REACHED");
  const cInd = at("INDUSTRIAL_REACHED");
  const cAtom = at("ATOMIC_REACHED");
  const cSpace = at("SPACE_REACHED");
  const cBossKill = at("BOSS_KILLED");
  if (cStone && cBronze) L.push(`  - Stone dwell: ${f2(cBronze.simTime - cStone.simTime)}s`);
  if (cBronze && cIron) L.push(`  - Bronze dwell: ${f2(cIron.simTime - cBronze.simTime)}s`);
  if (cIron && cInd) L.push(`  - Iron dwell: ${f2(cInd.simTime - cIron.simTime)}s`);
  if (cInd && cAtom) L.push(`  - Industrial dwell: ${f2(cAtom.simTime - cInd.simTime)}s`);
  if (cAtom && cSpace) L.push(`  - Atomic dwell: ${f2(cSpace.simTime - cAtom.simTime)}s`);
  if (cSpace && cBossKill) L.push(`  - Space to Boss kill: ${f2(cBossKill.simTime - cSpace.simTime)}s`);
  L.push(``);
  L.push(`## Engagement Identity`);
  for (const g of snap.engagement ?? []) {
    L.push(`- @${f2(g.simTime)}s ${g.age} asc ${g.ascension}: origin ${g.origin} [${g.families}] ` +
      `lv${g.level} ${g.weapons} techs ${g.techs} knowledge ${g.knowledge} ` +
      `breakthroughs [${(g.breakthroughs ?? []).join("+") || "-"}] legacies [${(g.legacies ?? []).join("+") || "-"}] ` +
      `poi [${(g.poiClaims ?? []).join("+") || "-"}]`);
  }
  if ((snap.engagement ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Knowledge At Age`);
  for (const k of snap.ageKnowledge ?? []) {
    L.push(`- ${k.age} @${f2(k.simTime)}s (asc ${k.ascension}): ${k.knowledge}`);
  }
  if ((snap.ageKnowledge ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Sim Decisions (ordered)`);
  for (const m of (snap.simMarks ?? []).slice(0, 200)) {
    L.push(`- [${m.kind}] ${m.detail} @${f2(m.simTime)}s ${m.age} asc ${m.ascension}`);
  }
  if ((snap.simMarks ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Performance Summary`);
  for (const p of snap.perfCheckpoints ?? []) {
    L.push(`- ${p.label}: n=${p.samples} fpsMin=${Math.round(p.fpsMin)} ` +
      `frame ${f2(p.frameP50)}/${f2(p.frameP95)}/${f2(p.frameP99)}ms ` +
      `sim ${f2(p.simP50)}/${f2(p.simP95)}/${f2(p.simP99)}ms ` +
      `ent ${p.enemiesMax}/${p.projsMax}/${p.pickupsMax}`);
  }
  if ((snap.perfCheckpoints ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Assertions / Errors`);
  const fails = (snap.assertions ?? []).filter((a) => !a.pass);
  L.push(`- failed assertions: ${fails.length}`);
  for (const a of fails.slice(0, 50)) L.push(`  - [FAIL] ${a.id} — ${a.name}: ${a.detail}`);
  const errs = (snap.consoleEntries ?? []).filter((x) => x.level === "error");
  L.push(`- console errors: ${errs.length}`);
  for (const e of errs.slice(0, 20)) L.push(`  - ${e.message}`);
  L.push(``);
  L.push(`## Human Ratings (recorded, never inferred)`);
  if ((snap.ratings ?? []).length === 0) L.push(`- not provided`);
  for (const r of snap.ratings ?? []) L.push(`- ${r.question}: ${r.score}/5`);
  L.push(``);
  L.push(`## Human Feedback Marks (optional)`);
  if ((snap.feedback ?? []).length === 0) L.push(`- none pressed (neutral — not positive, not negative)`);
  for (const fb of (snap.feedback ?? []).slice(0, 100)) {
    L.push(`- [${fb.category}] [${fb.label}] ${fb.note || "(no note)"} @${f2(fb.simTime)}s ${fb.age}`);
  }
  L.push(``);
  L.push(`## Human Comment (optional)`);
  L.push(``);
  L.push(snap.humanComment ? `- comment: "${snap.humanComment}"` : `- comment: NOT PROVIDED`);
  L.push(``);
  return L.join("\n");
}

function main() {
  if (!existsSync(LATEST)) {
    console.error(`No QA report yet: ${LATEST} — play ?qa=1 to target-complete first.`);
    process.exit(1);
  }
  const snap = JSON.parse(readFileSync(LATEST, "utf8"));
  if (!snap || typeof snap !== "object" || !Array.isArray(snap.checkpoints)) {
    console.error("latest.json is not a recorder snapshot — refusing to summarize.");
    process.exit(1);
  }
  const md = buildSanitizedMarkdown(snap);
  const outPath = getReportOutputPath(snap);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, md, "utf8");
  console.log(`wrote ${outPath}`);

  // Write independent session file if sessionId is present
  if (snap.sessionId && (snap.versions?.content ?? 0) >= 8) {
    const sessionOut = join(ROOT, "docs", "playtests", `session-${snap.sessionId}-sanitized.md`);
    writeFileSync(sessionOut, md, "utf8");
    console.log(`wrote session report: ${sessionOut}`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
