// qa:report — sanitized, repo-safe playtest summary (committable).
// Reads test-results/human-playtests/latest.json, writes
// docs/playtests/latest-v020-engagement.md with project evidence ONLY.
// Raw environment fingerprints / local paths / user data never leave the machine.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const LATEST = join(ROOT, "test-results", "human-playtests", "latest.json");
const OUT = join(ROOT, "docs", "playtests", "latest-v020-engagement.md");

const f2 = (n) => (Number.isFinite(n) ? n.toFixed(2) : "n/a");

/** Build the sanitized markdown from a raw recorder snapshot. Pure-ish, tested. */
export function buildSanitizedMarkdown(snap) {
  const L = [];
  const cps = snap.checkpoints ?? [];
  const at = (name) => cps.find((c) => c.event === name);
  const t = (name) => {
    const c = at(name);
    return c ? `${f2(c.simTime)}s sim` : "NOT REACHED";
  };
  L.push(`# v0.2 Human Engagement Test — Sanitized Evidence`);
  L.push(``);
  L.push(`> Auto-generated by \`npm run qa:report\` from local QA telemetry.`);
  L.push(`> Machine evidence only — fun and readability verdicts need a human.`);
  L.push(``);
  L.push(`## Run`);
  L.push(``);
  L.push(`- seed: ${snap.seed ?? "unknown"}`);
  L.push(`- package: ${snap.versions?.packageVersion ?? "?"} / worldgen ${snap.versions?.worldgen ?? "?"} / content ${snap.versions?.content ?? "?"} / save ${snap.versions?.saveSchema ?? "?"}`);
  L.push(`- endReason: ${snap.endReason || "NOT FINISHED"}`);
  L.push(`- viewport: ${snap.environment?.viewport ?? "?"} / refresh: ${snap.environment?.refreshHz ?? "?"}`);
  L.push(``);
  L.push(`## Route`);
  for (const [ev, label] of [
    ["RUN_START", "run started"], ["BRONZE_REACHED", "Bronze"], ["IRON_REACHED", "Iron"],
    ["INDUSTRIAL_REACHED", "Industrial"], ["ATOMIC_REACHED", "Atomic"], ["SPACE_REACHED", "Space"],
    ["BOSS_SPAWNED", "boss spawned"], ["BOSS_KILLED", "boss killed"],
    ["ASCENSION_OFFERED", "ascension offered"], ["ASCENSION_STARTED", "ascension started"],
    ["CHILD_WORLD_STARTED", "child world"],
    ["POST_ASCENSION_30S", "post-ascension +30s"],
    ["POST_ASCENSION_60S", "post-ascension +60s"],
    ["POST_ASCENSION_120S", "post-ascension +120s"],
    ["PLAYER_DIED", "player died"], ["RUN_END", "run ended"],
  ]) {
    L.push(`- [${at(ev) ? "x" : " "}] ${label} ${at(ev) ? `(${f2(at(ev).simTime)}s)` : ""}`);
  }
  L.push(``);
  L.push(`## Engagement Identity`);
  for (const g of snap.engagement ?? []) {
    L.push(`- @${f2(g.simTime)}s ${g.age} asc ${g.ascension}: origin ${g.origin} [${g.families}] ` +
      `lv${g.level} ${g.weapons} techs ${g.techs} knowledge ${g.knowledge} ` +
      `breakthroughs [${(g.breakthroughs ?? []).join("+") || "-"}] legacies [${(g.legacies ?? []).join("+") || "-"}] ` +
      `poi [${(g.poiClaims ?? []).join("+") || "-"}]`);
  }
  if ((snap.engagement ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Knowledge At Age`);
  for (const k of snap.ageKnowledge ?? []) {
    L.push(`- ${k.age} @${f2(k.simTime)}s (asc ${k.ascension}): ${k.knowledge}`);
  }
  if ((snap.ageKnowledge ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Sim Decisions (ordered)`);
  for (const m of (snap.simMarks ?? []).slice(0, 200)) {
    L.push(`- [${m.kind}] ${m.detail} @${f2(m.simTime)}s ${m.age} asc ${m.ascension}`);
  }
  if ((snap.simMarks ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Performance Summary`);
  for (const p of snap.perfCheckpoints ?? []) {
    L.push(`- ${p.label}: n=${p.samples} fpsMin=${Math.round(p.fpsMin)} ` +
      `frame ${f2(p.frameP50)}/${f2(p.frameP95)}/${f2(p.frameP99)}ms ` +
      `sim ${f2(p.simP50)}/${f2(p.simP95)}/${f2(p.simP99)}ms ` +
      `ent ${p.enemiesMax}/${p.projsMax}/${p.pickupsMax}`);
  }
  if ((snap.perfCheckpoints ?? []).length === 0) L.push(`- none recorded`);
  L.push(``);
  L.push(`## Assertions / Errors`);
  const fails = (snap.assertions ?? []).filter((a) => !a.pass);
  L.push(`- failed assertions: ${fails.length}`);
  for (const a of fails.slice(0, 50)) L.push(`  - [FAIL] ${a.id} — ${a.name}: ${a.detail}`);
  const errs = (snap.consoleEntries ?? []).filter((x) => x.level === "error");
  L.push(`- console errors: ${errs.length}`);
  for (const e of errs.slice(0, 20)) L.push(`  - ${e.message}`);
  L.push(``);
  L.push(`## Human Ratings (recorded, never inferred)`);
  if ((snap.ratings ?? []).length === 0) L.push(`- not provided`);
  for (const r of snap.ratings ?? []) L.push(`- ${r.question}: ${r.score}/5`);
  L.push(``);
  L.push(`## Human Feedback Marks (optional)`);
  if ((snap.feedback ?? []).length === 0) L.push(`- none pressed (neutral — not positive, not negative)`);
  for (const fb of (snap.feedback ?? []).slice(0, 100)) {
    L.push(`- [${fb.category}] [${fb.label}] ${fb.note || "(no note)"} @${f2(fb.simTime)}s ${fb.age}`);
  }
  L.push(``);
  return L.join("\n");
}

function main() {
  if (!existsSync(LATEST)) {
    console.error(`No QA report yet: ${LATEST} — play ?qa=1 to target-complete first.`);
    process.exit(1);
  }
  const snap = JSON.parse(readFileSync(LATEST, "utf8"));
  if (!snap || typeof snap !== "object" || !Array.isArray(snap.checkpoints)) {
    console.error("latest.json is not a recorder snapshot — refusing to summarize.");
    process.exit(1);
  }
  const md = buildSanitizedMarkdown(snap);
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, md, "utf8");
  console.log(`wrote ${OUT}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
